package z.homework;

public class Rectangle extends Shape {

	// fields
	private double length;
	private double width;

	// CTOR 1
	public Rectangle(String color, double length, double width) {
		super(color);
		this.length = length;
		this.width = width;
	}

	// CTOR 2
	public Rectangle(double side) {
		this("black", side, side);
	}

	// methods
	@Override
	public double getArea() {
		return length * width;
	}

	// getters and setters (generated by eclipse
	public double getLength() {
		return length;
	}

	public void setLength(double length) {
		this.length = length;
	}

	public double getWidth() {
		return width;
	}

	public void setWidth(double width) {
		this.width = width;
	}

}
